version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase # ชื่อ database
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: mypassword # password database
    ports:
      - "5432:5432"
