version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Map the root project directory
    working_dir: /app  # Ensure the container starts in the right directory
    depends_on:
      - localhost  # Changed from localhost to db

  localhost:  # Changed the service name to db
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    expose:
      - "5432"
